# build.yaml (in repo root)
---
include:
  - board: nice_nano_v2
    shield: split_left
    cmake-args: "-DZMK_SPLIT_ROLE=central"
    artifact-name: left-half

  - board: nice_nano_v2
    shield: split_right
    cmake-args: "-DZMK_SPLIT_ROLE=peripheral"
    artifact-name: right-half
