# west.yml (in repo root)
manifest:
  remotes:
    - name: zmk
      url-base: https://github.com/zmkfirmware
    - name: zephyrproject
      url-base: https://github.com/zephyrproject-rtos
  projects:
    - name: zmk
      remote: zmk
      repo-path: app
      revision: main
      import: app/west.yml
    - name: zephyr
      remote: zephyrproject
      repo-path: modules/zephyr
      revision: v3.5.0
    - name: hal_nordic
      remote: zephyrproject
      repo-path: modules/hal/nordic
      revision: main
    - name: nrfx
      remote: zephyrproject
      repo-path: modules/hal/nordic/nrfx
      revision: main
    - name: nrfxlib
      remote: zephyrproject
      repo-path: modules/hal/nordic/nrfxlib
      revision: main
