# config/west.yml
manifest:
  defaults:
    remote: zmk
  remotes:
    - name: zmk
      url-base: https://github.com/zmkfirmware
    - name: zephyrproject
      url-base: https://github.com/zephyrproject-rtos

  projects:
    # 1) ZMK firmware (imports its own sub‐manifest app/west.yml)
    - name: zmk
      remote: zmk
      repo-path: app
      revision: main
      import: app/west.yml

    # 2) Zephyr RTOS
    - name: zephyr
      remote: zephyrproject
      repo-path: modules/zephyr
      revision: v3.5.0

    # 3) Nordic HAL modules
    - name: hal_nordic
      remote: zephyrproject
      repo-path: modules/hal/nordic
      revision: main
    - name: nrfx
      remote: zephyrproject
      repo-path: modules/hal/nordic/nrfx
      revision: main
    - name: nrfxlib
      remote: zephyrproject
      repo-path: modules/hal/nordic/nrfxlib
      revision: main
