name: Build ZMK firmware
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      config_path: config         # points to config/west.yml + boards/shields/
      # build_matrix_path: build.yaml  # default, so can omit
      # archive_name: firmware         # optional override
      # fallback_binary: bin            # optional override
