name: ZMK Split Keyboard CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - board: nice_nano_v2
            shield: split_left
            role: central
            artifact: left-half
          - board: nice_nano_v2
            shield: split_right
            role: peripheral
            artifact: right-half

    defaults:
      run:
        shell: bash

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          cmake \
          ninja-build \
          device-tree-compiler \
          gcc-arm-none-eabi \
          python3-pip \
          python3-setuptools

    - name: Install West
      run: |
        python3 -m pip install --user west
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Init & update ZMK
      run: |
        cd app
        west init -l .
        west update

    - name: Source Zephyr environment
      run: |
        cd app
        source scripts/zephyr-env.sh

    - name: Build ${{ matrix.shield }} (${matrix.role})
      run: |
        cd app
        source scripts/zephyr-env.sh
        west build -b ${{ matrix.board }} -d ../build/${{ matrix.shield }} \
          -- \
          -DSHIELD=${{ matrix.shield }} \
          -DZMK_SPLIT_ROLE=${{ matrix.role }}

    - name: Upload ${{ matrix.artifact }} UF2
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact }}-uf2
        path: build/${{ matrix.shield }}/zephyr/zmk.uf2
