name: ZMK Split Keyboard CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Cache Python packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Cache West & Zephyr build
      uses: actions/cache@v3
      with:
        path: |
          ~/.west
          app/modules
          app/modules/zephyr
        key: ${{ runner.os }}-west-${{ hashFiles('**/west.yml') }}
        restore-keys: |
          ${{ runner.os }}-west-

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          git zip cmake ninja-build device-tree-compiler \
          gcc-arm-none-eabi python3-pip python3-setuptools python3-distutils

    - name: Install West
      run: |
        python3 -m pip install --user west
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Init & update ZMK (West)
      run: |
        cd app
        west init -l .
        west update

    - name: Source Zephyr environment
      run: |
        cd app
        source scripts/zephyr-env.sh

    - name: Build LEFT half (central)
      run: |
        cd app
        source scripts/zephyr-env.sh
        west build -b nice_nano_v2 -d ../build/left \
          -- -DSHIELD=split_left -DZMK_SPLIT_ROLE=central

    - name: Build RIGHT half (peripheral)
      run: |
        cd app
        source scripts/zephyr-env.sh
        west build -b nice_nano_v2 -d ../build/right \
          -- -DSHIELD=split_right -DZMK_SPLIT_ROLE=peripheral

    - name: Upload LEFT UF2
      uses: actions/upload-artifact@v4
      with:
        name: left-half-uf2
        path: build/left/zephyr/zmk.uf2

    - name: Upload RIGHT UF2
      uses: actions/upload-artifact@v4
      with:
        name: right-half-uf2
        path: build/right/zephyr/zmk.uf2
